call build-common.bat

Set ARCHIVE=ogre_src_v1-8-1.tar.bz2
Set DEP_ARCHIVE=cabalistic-ogredeps-0e96ef9d3475.zip
Set BUILD_DIR=%BUILD_ROOT%/ogre_src_v1-8-1
Set BUILD_DIR_DEPS=%BUILD_ROOT%/cabalistic-ogredeps-0e96ef9d3475
Set PREFIX=%cd%/ogre/
Set PREFIX_DEPS=%cd%/misc/

echo "Compile Ogre"

echo "Extracting OgreDeps"
if not exist %BUILD_ROOT% exit
cd %BUILD_ROOT%

if exist %BUILD_DIR_DEPS% RD /S /Q "%BUILD_DIR_DEPS%"

winrar.exe x %EX_DIR%/%DEP_ARCHIVE%

if not exist %BUILD_DIR_DEPS% exit

echo "Configuring OgreDeps"
cd %BUILD_DIR_DEPS%
cmake -DCMAKE_INSTALL_PREFIX:PATH=%PREFIX_DEPS% -DOGREDEPS_BUILD_OIS=OFF .

echo "Building OgreDeps"
MSBuild.exe OGREDEPS.sln /p:Configuration=Release > NUL

echo "Installing OgreDeps"
MSBuild.exe INSTALL.vcxproj /p:Configuration=Release > NUL

echo "Cleaning up OgreDeps"
cd %DEP_DIR%
RD /S /Q "%BUILD_DIR_DEPS%"

xcopy /S /Y "%PREFIX_DEPS%/bin/Release" "%PREFIX_DEPS%/bin"
xcopy /S /Y "%PREFIX_DEPS%/lib/Release" "%PREFIX_DEPS%/lib"
rd /S /Q "%PREFIX_DEPS%/bin/Release"
rd /S /Q "%PREFIX_DEPS%/bin/Debug"
rd /S /Q "%PREFIX_DEPS%/lib/Release"
rd /S /Q "%PREFIX_DEPS%/lib/Debug"

echo "Extracting Ogre"
if not exist %BUILD_ROOT% exit
cd %BUILD_ROOT%

if exist %BUILD_DIR% RD /S /Q "%BUILD_DIR%"

winrar.exe x %EX_DIR%/%ARCHIVE%

if not exist %BUILD_DIR% exit

echo "Configuring Ogre"

cd %BUILD_DIR%

cmake -DOGRE_BUILD_COMPONENT_PAGING:BOOL=ON -DOGRE_BUILD_COMPONENT_PROPERTY:BOOL=ON -DOGRE_BUILD_COMPONENT_RTSHADERSYSTEM:BOOL=ON -DOGRE_BUILD_COMPONENT_TERRAIN:BOOL=ON -DOGRE_BUILD_PLUGIN_BSP:BOOL=ON -DOGRE_BUILD_PLUGIN_CG:BOOL=ON -DOGRE_BUILD_PLUGIN_OCTREE:BOOL=ON -DOGRE_BUILD_PLUGIN_PCZ:BOOL=ON -DOGRE_BUILD_PLUGIN_PFX:BOOL=ON -DOGRE_BUILD_RENDERSYSTEM_GL:BOOL=ON -DOGRE_BUILD_RENDERSYSTEM_D3D9=OFF -DOGRE_BUILD_RENDERSYSTEM_D3D11=OFF -DOGRE_BUILD_RTSHADERSYSTEM_CORE_SHADERS:BOOL=ON -DOGRE_BUILD_RTSHADERSYSTEM_EXT_SHADERS:BOOL=ON -DOGRE_BUILD_TESTS:BOOL=OFF -DOGRE_BUILD_SAMPLES:BOOL=OFF -DOGRE_BUILD_TOOLS:BOOL=ON -DOGRE_CONFIG_ALLOCATOR:STRING=1 -DOGRE_CONFIG_CONTAINERS_USE_CUSTOM_ALLOCATOR:BOOL=ON -DOGRE_CONFIG_DOUBLE:BOOL=OFF -DOGRE_CONFIG_ENABLE_DDS:BOOL=ON -DOGRE_CONFIG_ENABLE_FREEIMAGE:BOOL=ON -DOGRE_CONFIG_ENABLE_PVRTC:BOOL=OFF -DOGRE_CONFIG_ENABLE_VIEWPORT_ORIENTATIONMODE:BOOL=OFF -DOGRE_CONFIG_ENABLE_ZIP:BOOL=ON -DOGRE_CONFIG_MEMTRACK_RELEASE:BOOL=OFF -DOGRE_CONFIG_NEW_COMPILERS:BOOL=ON -DOGRE_CONFIG_STRING_USE_CUSTOM_ALLOCATOR:BOOL=OFF -DOGRE_CONFIG_THREADS:STRING=2 -DOGRE_CONFIG_DOUBLE:BOOL=ON -DOGRE_CONFIG_THREAD_PROVIDER:STRING=boost -DOGRE_FULL_RPATH:BOOL=OFF -DOGRE_INSTALL_DOCS:BOOL=OFF -DOGRE_INSTALL_SAMPLES:BOOL=OFF -DOGRE_INSTALL_SAMPLES_SOURCE:BOOL=OFF -DOGRE_INSTALL_TOOLS:BOOL=ON -DOGRE_LIB_DIRECTORY:STRING=lib -DOGRE_PROFILING:BOOL=OFF -DOGRE_STATIC:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=%PREFIX% -DOGRE_USE_BOOST:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=%DEP_DIR%/boost -DOIS_HOME=%DEP_DIR%/ois -DOGRE_DEPENDENCIES_DIR=%PREFIX_DEPS% .

echo "Building Ogre"
MSBuild.exe OGRE.sln /p:Configuration=Release > NUL

echo "Installing Ogre"
MSBuild.exe INSTALL.vcxproj /p:Configuration=Release > NUL

echo "Cleaning up"
cd %DEP_DIR%
RD /S /Q "%BUILD_DIR%"

xcopy /S /Y "%PREFIX%/bin/Release" "%PREFIX%/bin" > NUL
xcopy /S /Y "%PREFIX%/lib/Release" "%PREFIX%/lib" > NUL
rd /S /Q "%PREFIX%/bin/Release"
rd /S /Q "%PREFIX%/lib/Release"
rd /S /Q "%PREFIX%/include/OIS"
rd /S /Q "%PREFIX%/CMake"
