/**
 * Copyright 2012 FAU (Friedrich Alexander University of Erlangen-Nuremberg)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __I6ENGINE_UTILS_RANDOM_H__
#define __I6ENGINE_UTILS_RANDOM_H__

#include <mutex>
#include <random>

#include "i6engine/utils/Exceptions.h"
#include "i6engine/utils/Singleton.h"

#include "boost/date_time.hpp"

namespace i6engine {
namespace utils {

	/**
	 * \brief creates random numbers
	 */
	class ISIXE_UTILS_API Random : public Singleton<Random> {
		friend class Singleton<Random>;

	public:
		/**
		 * \brief destructor
		 */
		~Random() {
			delete _linear;
		}

		/**
		 * \brief returns a random number in range of unsigned int
		 */
		uint32_t rand() const {
			return getRand();
		}

		/**
		 * \brief returns a random number in the range between 0 and max ([0;max[)
		 */
		uint32_t rand(uint32_t max) const {
			if (max == 0) {
				ISIXE_THROW_API("i6eRandom", "max value has to be grater than zero")
			}
			return getRand() % max;
		}

		/**
		 * \brief returns a random number in the range between min and max ([min; max[)
		 */
		uint32_t rand(uint32_t min, uint32_t max) const {
			if (min >= max) {
				ISIXE_THROW_API("i6eRandom", "max value has to be greater than min value")
			}
			return (getRand() % (max - min)) + min;
		}

		/**
		 * \brief sets a random seed value
		 */
		void setSeed(uint32_t seed) {
			std::lock_guard<std::mutex> l(_lock);
			_linear->seed(seed);
		}

	private:
		/**
		 * \brief random generator
		 */
		std::minstd_rand * _linear;

		/**
		 * \brief lock for multithreaded access
		 */
		mutable std::mutex _lock;

		/**
		 * \brief returns the random number generated by intern generator
		 */
		uint32_t getRand() const {
			std::lock_guard<std::mutex> l(_lock);
			return (*_linear)();
		}

		/**
		 * \brief default constructor
		 */
		Random() : _linear(new std::minstd_rand(size_t(boost::posix_time::time_period(boost::posix_time::time_from_string("2010-03-19 14:23:10"), boost::posix_time::microsec_clock::universal_time()).length().total_microseconds()))), _lock() {
		}
	};

} /* namespace utils */
} /* namespace i6engine */

#endif /* __I6ENGINE_UTILS_RANDOM_H__ */
